BodSpeak/config/routes.rb
Bodspeak::Application.routes.draw do
  
  
  resources :users do
  collection do
    get 'check_email'
  end
  end
  
  namespace :api do
  resources :users, :defaults => { :format => 'xml' }
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  
  resources :doctors
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get "static_pages/home"
  
  get "doctor/show"

  get "static_pages/help"

  get "static_pages/about"
  
  get "static_pages/contact"
  
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

BodSpeak/app/models/message.rb
class Message < ActiveRecord::Base
  #The messsage model that references the user model
  attr_accessible :message,:user_id
  belongs_to :user
  validates :message, presence: true
  validates :user_id, presence: true
  default_scope order: 'messages.created_at DESC'
end

BodSpeak/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
#the message contrller takes care of all the messaging functionality in BodSpeak
  before_filter :signed_in_user

  def create
  @message = current_user.messages.build(params[:message])
    if @message.save
      flash[:success] = "Message created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end
  
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end
  
  def edit
  @message = Message.find(params[:id])
  end
  
  
  def update
  @message = Message.find(params[:id])

  if @message.update_attributes params[:message]
    flash[:notice] = 'The User is successfully updated!'
  end
end
end

BodSpeak/app/views/messages/_message.html.erb
<li>
  <span class="content"><%= message.message %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(message.created_at) %> ago.
  </span>
  
  </li>

BodSpeak/app/views/messages/_message_form.html.erb
<%= form_for :message, :url => {:action => :create} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :message, placeholder: "Type your message here..." %>
  </div>
  <%= f.submit "Send", class: "btn btn-large btn-primary" %>
<% end %>

BodSpeak/app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'message_form' %>

BodSpeak/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @message.message %>
</p>

<p>
  <b>User:</b>
  <%= @message.user_id %>
</p>
<section>
        <%= render 'shared/message_form' %>
      </section>


<%= link_to 'Back', messages_path %>