BodSpeak/config/routes.rb
Bodspeak::Application.routes.draw do
  
  
  resources :users do
  collection do
    get 'check_email'
  end
  end
  
  namespace :api do
  resources :users, :defaults => { :format => 'xml' }
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  
  resources :doctors
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get "static_pages/home"
  
  get "doctor/show"

  get "static_pages/help"

  get "static_pages/about"
  
  get "static_pages/contact"
  
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

BodSpeak/app/views/layouts/_footer.html.erb
<footer class="footer">
  
</footer>

BodSpeak/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BodSpeak", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
		
		
		
		
		
		
		
          <li><%= link_to "Home", root_path %></li>
		  
		  
		  
		  
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

BodSpeak/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

BodSpeak/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
	  
    </div>
  </body>
</html>