BodSpeak/config/routes.rb
Bodspeak::Application.routes.draw do
  
  
  resources :users do
  collection do
    get 'check_email'
  end
  end
  
  namespace :api do
  resources :users, :defaults => { :format => 'xml' }
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  
  resources :doctors
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get "static_pages/home"
  
  get "doctor/show"

  get "static_pages/help"

  get "static_pages/about"
  
  get "static_pages/contact"
  
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

BodSpeak/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  has_one :patient_info
  attr_accessible :name, :email, :password, :password_confirmation,:user_type,:patient_infos_attributes
  has_secure_password
  has_many :messages, dependent: :destroy
  

  accepts_nested_attributes_for :patient_info

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  before_save :default_value

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
	
	def default_value
	self.user_type ||= 'P'
	end
end

BodSpeak/app/controllers/Api/users_controller.rb
class Api::UsersController < ApplicationController
 #User controller to handle user -realted actions
 
  http_basic_authenticate_with :name => "Jisha", :password => "password"

  before_filter :fetch_user, :except => [:index, :create]

 def fetch_user
    @user = User.find_by_id(params[:id])
  end

  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @user }
      format.xml { render xml: @user }
    end
  end

  def create
    @user = User.new(params[:user])
	#Giving a temporary password to create the user
     @user.password='password'
   @user.password_confirmation='password'
   
    respond_to do |format|
      if @user.save
        format.json { render json: @user, status: :created }
        format.xml { render xml: @user, status: :created }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
	
      if @user.update_attributes(params[:user])

        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

BodSpeak/app/controllers/users_controller.rb
class UsersController < ApplicationController

#User controller to create and maintain users.
respond_to :html, :js
def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    end
  
  def create
    @user = User.new(params[:user])
	respond_to do |format|
      if @user.save	  
	  sign_in @user
	  format.html { redirect_to(@user, :notice => 'Post created.') }  
       format.js 
	#  flash[:success] = "Welcome to the Sample App!"
    #  redirect_to @user
    else
	format.html { render :action => "new" }  
        format.js 
      #render 'new'
    end
	end
  end
  
  def check_email
    @user = User.find_by_email(params[:user]['email'])
    result = Hash.new
    result["isavailable"] = (@user == nil) ? true : false
    result["email"] = params[:user]['email']
    render json: result
  end
  
  def show
@user = User.find(params[:id])
    @messages = @user.messages.paginate(page: params[:page])
  end
end

class Api::UsersController < ApplicationController
  http_basic_authenticate_with :name => "Jisha", :password => "password"

  #skip_before_filter :authenticate_user! 
  before_filter :fetch_user, :except => [:index, :create]

 def fetch_user
    @user = User.find_by_id(params[:id])
  end

  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @user }
      format.xml { render xml: @user }
    end
  end

  def create
    @user = User.new(params[:user])
   # @user.temp_password = Devise.friendly_token
    respond_to do |format|
      if @user.save
        format.json { render json: @user, status: :created }
        format.xml { render xml: @user, status: :created }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

BodSpeak/app/helpers/users_helper.rb
module UsersHelper
end

BodSpeak/app/views/users/create.js.erb
$('body').html("<h1><%= escape_javaScript(@user.name) %></h1>").append("<%= escape_javaScript(@user.email) %>");

BodSpeak/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email  %>
	  <div id ="email_check"></div>
        <%= f.text_field :email,:data => {:remote => true, "url" => "/users/check_email", "data-type" => :json} %>
	  <div id="email_check"></div>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
	  <!-- Here starts the sidebar
	  <%= f.fields_for :patient_infos do |p| %>
	  <%= p.label :age, "Age" %>
	  <%= p.text_field :age %>
	  <%= p.label :anonymous, "Anonymous" %>
	  <%= p.text_field :anonymous %>
	  <%= p.label :gender, "Gender" %>
	  <%= p.text_field :gender %>
	  <% end %>
	  -->

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

BodSpeak/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
          <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.messages.any? %>
      <h3>Messages (<%= @user.messages.count %>)</h3>
      <ol class="messages">
        <%= render @messages %>
      </ol>
	  
      <%= will_paginate @messages %>
    <% end %>
	<%= link_to "New Message" , static_pages_home_path %>
  </div>
  
</div>